[build]
  command = "echo 'No build command needed for edge functions'"

[[edge_functions]]
  function = "mcp"
  path = "/mcp"

[functions]
  # Edge functions are billed differently than regular functions
  # Free tier: 3 million edge function requests/month
  # This is much more cost-effective than regular functions
  node_bundler = "esbuild"

